// enums/actions.enum.ts
export enum Actions {
    KNOWN_ACCOUNTS = 'KNOWN_ACCOUNTS',
    TOKEN_BALANCES = 'TOKEN_BALANCES',
    TOKENS = 'TOKENS',
    HELP = 'HELP',
    CLOSE = 'CLOSE',
    CANCEL = 'CANCEL',
    MAIN_MENU = 'MAIN_MENU',
}

export enum SceneActions {
    FILTER_AGAIN = 'FILTER_AGAIN',
    TOKEN_BALANCES_AGAIN = 'TOKEN_BALANCES_AGAIN',
    TOKENS_AGAIN = 'TOKENS_AGAIN',
    CLOSE_BUTTON = 'CLOSE_BUTTON',
    CANCEL_BUTTON = 'CANCEL_BUTTON',
    FETCH_ALL = 'FETCH_ALL',
}
