export enum Commands {
    KnownAccounts = 'knownaccounts',
    TokenBalances = 'tokenbalances',
    Tokens = 'tokens',
    TokenHolders = 'tokenholders',
    TokenDetails = 'tokendetails',
    TokenVolume = 'tokenvolume',
    TokenHoldersTs = 'tokenholdersts',
    TokenTransfers = 'tokentransfers',
    TokenTrades = 'tokentrades',
    Programs = 'programs',
    HELP = 'help',
    MAIN_MENU = 'main_menu',
    Cancel = 'cancel',
}
