export enum Commands {
    KnownAccounts = 'knownaccounts',
    TokenBalances = 'tokenbalances',
    TokenBalancesTs = 'tokenbalancests',
    Tokens = 'tokens',
    TokenHolders = 'tokenholders',
    TokenDetails = 'tokendetails',
    TokenVolume = 'tokenvolume',
    TokenHoldersTs = 'tokenholdersts',
    TokenTransfers = 'tokentransfers',
    TokenTrades = 'tokentrades',
    Programs = 'programs',
    ProgramTxCount = 'programtxcount',
    ProgramIxCount = 'programixcount',
    ProgramActiveUsersTs = 'programactiveusersts',
    ProgramActiveUsers = 'programactiveusers',
    ProgramDetails = 'programdetails',
    ProgramRanking = 'programranking',
    HELP = 'help',
    MAIN_MENU = 'main_menu',
    Cancel = 'cancel',
}
